### ISSUE TITLE
Issue about sh file parameters to reproduce the results of the TADPOLE challenge in the paper

### ISSUE THREAD

**Issue by CUI-J** [SsGood/MMGL#1]
Hello, I am very interested in your work and started trying to reproduce this work. I'm validating based on the TADPOLE challenge data first, but based on your script, the training and testing results are much lower than what is reported in your paper. In addition, I see in your Readme file that the configuration based on that sh file can reproduce the results in the paper, but I tried it and the performance was poor. Therefore, I would like to ask if there are other parameters that need to be set? Looking forward to your reply, thanks!

**Comment by SsGood** [comment]
I'm so sorry! 
The data preprocessing causes the problem, I can't believe I forgot to standardize the data when I reorganized the codes.
Now I upload a new .ipynb file for data preprocessing of TADPOLE, which fixes the bug. Now you could run the code on the data after standardization, and get a normal result.
But since I cannot guarantee the step of data_standardization after the reorganization is as same as the original code, I will upload a new .sh file to reproduce the result a few days later.

Thank you for your help in making us find this bug！

**Comment by CUI-J** [comment]
Thank you for your reply. 
After you modified the data processing code, the results of the experiment have been greatly improved. Based on the current .sh file configuration, I tried to run the TADPOLE three-category experiment. The test acc and auc are 91.47% and 92.42% respectively, which are very close to the results reported in the paper! 

Very grateful for your help!

**Comment by ZeinabRahbar** [comment]
@CUI-J Hi, can you provide me with the TAdpole data please
