### ISSUE TITLE
TADPOLE dataset seems 

### ISSUE THREAD

**Issue by xudunyuan** [SsGood/MMGL#4]

**Comment by xudunyuan** [comment]
When I try to execute the command:
python main.py --GC_mode weighted-cosine --MF_mode concat --MP_mode GCN --datname TADPOLE --dropout 0 --lr 0.0055 --mode simple-2 --n_head 2 --n_hidden 18 --nlayer 3 --reg 0.26
It reports: [Errno 2] No such file or directory: './data/TADPOLE/modal_feat_dict.npy'

And when I try to run the .ipynb file inside the MMGL/data/TADPOLE
it reports: [Errno 2] No such file or directory: './6-tadpole_challenge/TADPOLE_D1_D2_Dict.csv'

Could you upload these data files?
Thanks!

**Comment by SsGood** [comment]
Thanks a lot for your attention to our work！
But sadly, I have to apologize that I cannot release the files of TADPOLE publicly since the authorization problem of the ADNI database. Unlike the ABIDE database which is open access, The file 'TADPOLE_D1_D2_Dict.csv' from the ADNI database is protected.

You can access the data in the following ways. Firstly, go to [https://adni.loni.usc.edu/data-samples/access-data/](https://adni.loni.usc.edu/data-samples/access-data/) to apply for access to data. Then, you can download the data of the TADPOLE dataset.
![image](https://user-images.githubusercontent.com/38525791/199938079-2941414b-3dcb-4168-bba2-96b77a9edeb1.png)

**Comment by ZeinabRahbar** [comment]
@SsGood  Hi, this link does not work
