### ISSUE TITLE
Can your check please the feature selection function in TADPOLE preprocessing file?

### ISSUE THREAD

**Issue by aldiak** [SsGood/MMGL#8]
Greetings Sir, I am getting the following error related to feature selection function:

selector = RFE(estimator, num_features_selected, step=200, verbose=1)
TypeError: __init__() takes 2 positional arguments but 3 positional arguments (and 2 keyword-only arguments) were given

**Comment by SsGood** [comment]
I'm sorry for this question that may be caused by the version of scikit-learn. 
An easy solution is you can re-run the codes again under scikit-learn == 0.19.1.  

In my environment with scikit-learn == 0.19.1,  the code can be executable, and a **_future warning_** would be thrown as
![image](https://user-images.githubusercontent.com/38525791/227128568-9c94ae2d-8d82-43b8-832a-acc15480d6a3.png)
so you may also try to pass n_features_to_select=150 as keyword args instead of positional arguments to solve the problem.
![image](https://user-images.githubusercontent.com/38525791/227129601-16e363b4-8802-40c7-b591-800e4f05b23a.png)
Hope it can help you!

**Comment by aldiak** [comment]
Hi, it’s ok. I solved the issue. Thanks

**Comment by ZeinabRahbar** [comment]
@aldiak Hi, I want to know how you found the tadpole dataset version that was used here?

**Comment by aldiak** [comment]
Hi, could you please follow the instructions here:
https://tadpole.grand-challenge.org/Data/

**Comment by ZeinabRahbar** [comment]
@aldiak Thank you.
